// spa-react/src/components/AppHeader.jsx
import CustomLink from "./CustomLink";

function AppHeader() {
  const h1Text = "SPA React";
  return (
    <header>
      <nav>
        <h1>{h1Text}</h1>
        <CustomLink to="/">Home</CustomLink>
        <CustomLink to="/about">About</CustomLink>
        <CustomLink to="/contact">Contact</CustomLink>
      </nav>
    </header>
  );
}

export default AppHeader

// spa-vue/src/components/AppHeader.vue
<template>
  <header>
    <nav>
      <h1>{{ h1Text }}</h1>
      <router-link to="/">Home</router-link>
      <router-link to="/about">About</router-link>
      <router-link to="/contact">Contact</router-link>
    </nav>
  </header>
</template>

<script setup>
import { ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
const route = useRoute()
const router = useRouter()
const h1Text = ref('')
const h1TextMap = {
  '/': 'Home',
  '/about': 'About',
  '/contact': 'Contact',
}
watch(() => route.path, () => {
  h1Text.value = h1TextMap[route.path]
}, { immediate: true })
</script>
